site_name: "Algoritmos de Ordenação"
site_url: "https://guievbs.github.io/sorting-algorithms/" # Substitua pelo URL do GitHub
repo_url: "https://github.com/guievbs/sorting-algorithms" # Substitua pelo URL do GitHub
repo_name: "sorting-algorithms"
site_dir: site

theme:
  favicon: docs\favicon.ico
  icon:
    repo: fontawesome/brands/github
  name: material
  language: pt
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - macros
  - mkdocs-video
  - search:
      lang: pt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/guievbs
