name: CI for MkDocs Site

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente onde o job será executado

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material 
        pip install mkdocs-material[plugins]
        pip install mkdocs-glightbox mkdocs-video mkdocs-git-revision-date-localized-plugin mkdocs-exclude
        pip install mkdocs-macros-plugin  # Instalar o plugin macros

    - name: Build MkDocs site
      run: mkdocs build  # Gera o site

    - name: Deploy MkDocs site to GitHub Pages
      run: mkdocs gh-deploy --force  # Faz o deploy do site para o GitHub Pages
