name: ci
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Atualização do sistema
        run: sudo apt update
        
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar requirements
        run: pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build  # Gera o site

      - name: Deploy MkDocs site to GitHub Pages
        run: mkdocs gh-deploy --force  # Faz o deploy do site para o GitHub Pages
